- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/events_controller.rb
- app/controllers/members_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/task_members_controller.rb
- app/controllers/tasks_controller.rb
- app/policies/application_policy.rb
- test/controllers/events_controller_test.rb
- test/controllers/members_controller_test.rb
- test/controllers/messages_controller_test.rb
- test/controllers/task_members_controller_test.rb
- test/controllers/tasks_controller_test.rb
basic install of pundit
Added controllers for events, members, tasks, task_members and messages
> Added pundit and Controllers

- Gemfile
- Gemfile.lock
added cloudinary gem to the project
> added clouddinary gem to gemfile

- Gemfile.lock
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_grey_button.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
Added a few partials - 'brand-btn' for the purple button and 'grey-btn' for grey. Added $purple and $hovered-purple variables. Drafted the landing page.
> first draft of landing page design, button partials

- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/policies/event_policy.rb
- app/policies/task_policy.rb
- app/policies/user_policy.rb
- app/views/layouts/application.html.erb
- app/views/users/confirmations/new.html.erb
- app/views/users/dashboard.html.erb
- app/views/users/mailer/confirmation_instructions.html.erb
- app/views/users/mailer/email_changed.html.erb
- app/views/users/mailer/password_change.html.erb
- app/views/users/mailer/reset_password_instructions.html.erb
- app/views/users/mailer/unlock_instructions.html.erb
- app/views/users/passwords/edit.html.erb
- app/views/users/passwords/new.html.erb
- app/views/users/registrations/edit.html.erb
- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
- app/views/users/shared/_error_messages.html.erb
- app/views/users/shared/_links.html.erb
- app/views/users/unlocks/new.html.erb
- test/controllers/users_controller_test.rb
- test/policies/event_policy_test.rb
- test/policies/task_policy_test.rb
- test/policies/user_policy_test.rb
Setup the dashboard and got a rough sketch going.
Will work further on getting it looking better and clean up the code with partials.
> Dashboard setup and rough sketch for frontend

- app/assets/stylesheets/components/_dashboard_event.scss
- app/assets/stylesheets/components/_dashboard_task.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/policies/event_policy.rb
- app/views/users/_dashboard_event.html.erb
- app/views/users/_dashboard_task.html.erb
- app/views/users/dashboard.html.erb
Hard-coded task and event info for the dashboard.
Need to update seeds to properly use tasks and events from a user's dashboard.
May still add sub-headers but for now they seem pretty easy to understand.
> Dashboard front end

- app/assets/stylesheets/components/_dashboard_event.scss
- app/assets/stylesheets/components/_dashboard_task.scss
- app/policies/task_policy.rb
- app/views/users/_dashboard_event.html.erb
- app/views/users/_dashboard_task.html.erb
- app/views/users/dashboard.html.erb
Did some initial swaps - still need to come back when seeds are done.
Also made some minor changes to the css to deal with lengthy task names and descriptions
.
> Dashboard swapout fake for real - progress

- app/assets/stylesheets/pages/_events_new.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/events_controller.rb
- app/policies/event_policy.rb
- app/views/events/new.html.erb
Made a simple form for creating an event.
Still could be styled more.
Want to add the ability to upload files (maybe even drag and drop) instead of URL - when the main journey is complete maybe...
> Event#new form page

- app/views/pages/home.html.erb
Just added the dashboard link to landing page and changed the wording on the button.
> fixed link on the landing page

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
Date and time added to navbar.
> added the date and time on the navbar

- app/assets/stylesheets/components/_dashboard_task.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_event_tasks.scss
- app/views/events/new.html.erb
- app/views/users/_dashboard_event.html.erb
- app/views/users/_dashboard_task.html.erb
- app/views/users/dashboard.html.erb
added task status with styles to keep positions uniform for all tasks.
also made pending the same purple as the buttons - maybe will change later to slightly lighter version.
> Dashboard front end additions

- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_events_new.scss
- app/views/users/_dashboard_task.html.erb
fixed dashboard overflow on the bottom of the page and in the events container.
> fixed dashboard overflow on the bottom of the page and in the events

- app/assets/stylesheets/components/_members.scss
- app/assets/stylesheets/components/_sidenav.scss
- app/assets/stylesheets/pages/_event_tasks.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
Minor styling tweaks - added a border to task and members cards so they are more visible.
> added some minor styling details for cards

- app/views/shared/_main.html.erb
> updated event main page to use the actual event poster_url

- app/controllers/users_controller.rb
- app/models/user.rb
Now tasks are ordered with nearest 'end' date at the top.
Events are ordered with nearest start date at the top.
> Sorted tasks and events in dashboard

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_events_new.scss
- app/views/events/new.html.erb
Lightened the background blue, and did a first draft of the event#create form.
> Minor style alterations

- app/assets/stylesheets/pages/_events_new.scss
- app/views/events/new.html.erb
Will restyle later this afternoon, but functionality back to normal now.
> removed inline-styling to fix broken create event form

- app/assets/stylesheets/pages/_events_new.scss
- app/views/events/new.html.erb
Styled again with inline-style (sorry!)
Not sure if it breaks Heroku so no need to push before the presentation.
> create-event-form with inline-styling

- app/views/devise/sessions/new.html.erb
Just so that it is easier on the eyes when we have to sign in.
> basic styling for log-in form

- app/assets/stylesheets/pages/_events_new.scss
- app/controllers/events_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/poster_upload_options_controller.js
- app/views/events/new.html.erb
- app/views/events/show.html.erb
- app/views/users/_dashboard_event.html.erb
- app/views/users/_dashboard_task.html.erb
Added the option in the new event form to upload a file (the default) or paste a URL with a radio button for each.
Also updated the dashboard events/tasks to display properly, as well as the event show page.
> Poster url or file upload option

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
Hey guys, it is still a bit shitty but maybe 80% done. We can discuss any other ideas in the week.
> Landing page purple

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
Remove the sidebar and replaced it with translucent footer. Also removed hamburger menu and replaced with sign up and log out buttons.
> removed the sidebar and added translucent footer

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_messages.scss
- app/assets/stylesheets/pages/_home.scss
- app/channels/event_messages_channel.rb
- app/controllers/events_controller.rb
- app/controllers/messages_controller.rb
- app/javascript/controllers/event_messages_subscription_controller.js
- app/javascript/controllers/index.js
- app/javascript/controllers/tab_controller.js
- app/models/event.rb
- app/models/message.rb
- app/models/task.rb
- app/policies/message_policy.rb
- app/views/events/show.html.erb
- app/views/shared/_event_message.html.erb
- app/views/shared/_messages.html.erb
- config/routes.rb
- db/seeds.rb
- package.json
- test/channels/event_messages_channel_test.rb
- yarn.lock
Hi guys, this needs some work but want to push to check any aftershocks.
> set up the basics of the messages section

- app/assets/stylesheets/components/_messages.scss
- app/assets/stylesheets/config/_colors.scss
- app/controllers/messages_controller.rb
- app/javascript/controllers/event_messages_subscription_controller.js
- app/models/message.rb
- app/views/shared/_event_message.html.erb
- app/views/shared/_messages.html.erb
Finished the functionality and basic styling for the chat.
> functioning chat and styling for the general event room

- app/assets/stylesheets/components/_sidenav.scss
- app/channels/event_messages_channel.rb
- app/javascript/controllers/event_messages_subscription_controller.js
- app/views/shared/_sidenav.html.erb
Looks out of shape, but should be working
> turned the sidenav logo into a link

- app/javascript/controllers/index.js
fixed dashboard tasks marked done - line was deleted in application.js
> fixed dashboard tasks marked done - line was deleted in application.js

- app/assets/stylesheets/components/_dashboard_task.scss
- app/controllers/users_controller.rb
- app/views/shared/_main.html.erb
- app/views/users/_dashboard_event.html.erb
- app/views/users/_dashboard_task.html.erb
Added some minor style tweaks and fixes to the dashboard.
Also started to add extra information to bottom of Event#show main.
Need to ask TA in the morning for best approach (time saving) to adding this section.
> Dashboard style tweaks - started on Event#show main extra info

- app/assets/stylesheets/components/_messages.scss
- app/javascript/controllers/event_messages_subscription_controller.js
- app/views/messages/_messages_general.html.erb
- app/views/messages/_messages_roles.html.erb
- app/views/shared/_messages.html.erb
Sorry guys, this one is an incomplete attempt at getting the sub-group message rooms functioning. A failing attempt.
> attempted to create sub-groups for messages

- app/assets/stylesheets/components/_main.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/events/show.html.erb
- app/views/shared/_members.html.erb
Possible tab bar design, but easy to let go of so no worries if we go with something else :-)
> just an idea for the tab bar to give it more impact

- app/assets/stylesheets/components/_tabbar.scss
Widened the tab bar tabs so hopefully there is no gap between the tab links when hovered / active.
> widened the tabbar elements to fit wider screen

- app/assets/stylesheets/pages/_calendar.scss
- app/assets/stylesheets/pages/_home.scss
> added some styling to th calendar to make it more clear

- app/assets/stylesheets/pages/_home.scss
> made the landing page fully responsive. Bug on logo

- app/assets/stylesheets/components/_main_files.scss
- app/views/layouts/application.html.erb
- app/views/shared/_main.html.erb
- public/404.html
- public/500.html
> added download icons to promotion materials

- app/views/users/calendar.html.erb
Added: (end_attribute: :start_date,
> changed the calendar so that it shows only the start date

- app/assets/stylesheets/components/_messages.scss
- app/views/shared/_messages.html.erb
- app/views/shared/_navbar.html.erb
> minor styling on messages sidenav

- app/assets/stylesheets/components/_main.scss
- app/assets/stylesheets/components/_main_files.scss
- app/assets/stylesheets/components/_main_gear.scss
- app/views/shared/_main.html.erb
- app/views/shared/_main_gear.html.erb
- app/views/shared/_main_misc.html.erb
- app/views/shared/_main_timetable.html.erb
Possibly some conflicts in the sense of altering other elements on the app!
> styled the dashboard page with sizing and font-sizes

- app/assets/stylesheets/components/_main_gear.scss
- app/views/components/_gear_item.html.erb
- app/views/components/_misc_item.html.erb
- app/views/components/_timetable_set.html.erb
- app/views/shared/_main_gear.html.erb
- app/views/shared/_main_misc.html.erb
- app/views/shared/_main_timetable.html.erb
Lining up the contents at the top
> altered the styling for time, misc, gear boxes

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_main.scss
- app/views/events/show.html.erb
> title off of banner and styled card
